package org.opengb.routes

import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.response.respond
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import kotlinx.serialization.Serializable
import org.opengb.config.LandingConfig
import org.opengb.oauth.ClaimStore
import org.opengb.utility.UtilityRegistry

/**
 * `POST /claim/{code}` — atomic single-use redemption of a claim code generated by the
 * /connect/callback flow.
 *
 * Returns the encrypted refresh blob + derived proxy_token to the caller (Home Assistant) along
 * with the utility id and scope. The claim code is consumed regardless of whether the caller
 * successfully persisted the response — by design, callers retry by restarting the OAuth flow.
 */
fun Application.installClaim(
  claimStore: ClaimStore,
  registry: UtilityRegistry,
  currentApiVersion: String = CURRENT_API_VERSION,
) {
  routing {
    post("/claim/{code}") {
      val code = call.parameters["code"].orEmpty()
      if (code.isBlank()) {
        call.respond(HttpStatusCode.BadRequest, ErrorBody(error = "missing_code"))
        return@post
      }

      val record = claimStore.redeem(code)
      if (record == null) {
        call.respond(HttpStatusCode.Gone, ErrorBody(error = "claim_unknown_or_used"))
        return@post
      }

      call.respond(
        HttpStatusCode.OK,
        ClaimResponse(
          utilityId = record.utilityId,
          encryptedRefreshBlob = record.encryptedRefreshBlob,
          proxyToken = record.proxyToken,
          subscriptionUri = record.subscriptionUri,
          scope = record.scope,
          initialHistorySeconds = registry.require(record.utilityId).initialHistorySeconds,
          pollIntervalSeconds = registry.require(record.utilityId).pollIntervalSeconds,
          currentApiVersion = currentApiVersion,
        ),
      )
    }
  }
}

@Serializable
data class ClaimResponse(
  val utilityId: String,
  val encryptedRefreshBlob: String,
  val proxyToken: String,
  val subscriptionUri: String? = null,
  val scope: String? = null,
  /** Seconds of history the client should backfill on first fetch; from the utility profile. */
  val initialHistorySeconds: Long,
  /** Seconds between routine incremental polls; drives the client's `update_interval`. */
  val pollIntervalSeconds: Long,
  val currentApiVersion: String,
)

@Serializable
data class ErrorBody(val error: String, val message: String? = null)

/**
 * Stripe-style API version. Clients send `OpenGB-Api-Version: <date>` and the server's request
 * dispatch table picks the matching handler. Bumped only on breaking wire changes; old handlers
 * remain available for a deprecation window.
 */
const val CURRENT_API_VERSION = "2026-05-22"

/** Convenience: also exposed as a field on the [LandingConfig] in case the landing page wants it. */
@Suppress("unused")
private fun LandingConfig.apiVersionForHumans(): String = CURRENT_API_VERSION
